<?xml version="1.0"?>
<package format="3">
  <name>jamshield_recon_x_sim</name>
  <version>0.0.0</version>
  <description>ROS2 launch packaging for JamShield Recon-X runtime probes.</description>
  <maintainer email="noreply@jamshield.local">jamshield</maintainer>
  <license>Proprietary</license>

  <buildtool_depend>ament_python</buildtool_depend>

  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
